require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("./models/Product");

mongoose.connect(
  "mongodb+srv://mongotut:testing123@cluster0.hisj3ar.mongodb.net/shop_assessment_db"
);

const products = [
  {
    name: "Laptop Hp",
    imageUrl: "https://picsum.photos/id/870/200/300?grayscale&blur=2",
    amount: 5.24,
    currency: "EUR",
  },
  {
    name: "Cockatoo, red-breasted",
    imageUrl: "https://picsum.photos/id/870/200/300?grayscale&blur=2",
    currency: "IDR",
    amount: 2.75,
  },
  {
    name: "Savannah deer (unidentified)",
    imageUrl: "https://picsum.photos/id/870/200/300?grayscale&blur=2",
    currency: "CAD",
    amount: 2.13,
  },
  {
    name: "Gull, lava",
    imageUrl: "https://picsum.photos/id/870/200/300?grayscale&blur=2",
    currency: "CNY",
    amount: 1.25,
  },
  {
    name: "Lizard, mexican beaded",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "RUB",
    amount: 5.52,
  },
  {
    name: "Squirrel, antelope ground",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EUR",
    amount: 7.99,
  },
  {
    name: "Owl, white-browed",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 2.61,
  },
  {
    name: "Dove, little brown",
    imageUrl: "https://picsum.photos/200/300.webp",
    currency: "IDR",
    amount: 2.17,
  },
  {
    name: "Long-nosed bandicoot",
    imageUrl: "https://picsum.photos/200/300.webp",
    currency: "DOP",
    amount: 1.92,
  },
  {
    name: "Common wallaroo",
    imageUrl: "https://picsum.photos/200/300.webp",
    currency: "USD",
    amount: 7.4,
  },
  {
    name: "Roan antelope",
    imageUrl: "https://picsum.photos/200/300.webp",
    currency: "MXN",
    amount: 1.15,
  },
  {
    name: "Ground legaan",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "UZS",
    amount: 3.2,
  },
  {
    name: "Monster, gila",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 4.39,
  },
  {
    name: "Spider, wolf",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "VND",
    amount: 3.39,
  },
  {
    name: "Owl, snowy",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "IDR",
    amount: 4.3,
  },
  {
    name: "Violet-eared waxbill",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "BRL",
    amount: 1.66,
  },
  {
    name: "Bleu, blue-breasted cordon",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "CNY",
    amount: 8.14,
  },
  {
    name: "Bunting, crested",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "TJS",
    amount: 7.91,
  },
  {
    name: "Cape fox",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "CNY",
    amount: 6.53,
  },
  {
    name: "Western pygmy possum",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "CNY",
    amount: 9.04,
  },
  {
    name: "Southern sea lion",
    imageUrl: "https://picsum.photos/200/300/?blur=2",
    currency: "RUB",
    amount: 1.23,
  },
  {
    name: "Pelican, brown",
    imageUrl: "https://picsum.photos/200/300/?blur=2",
    currency: "CNY",
    amount: 6.57,
  },
  {
    name: "Cormorant, flightless",
    imageUrl: "https://picsum.photos/200/300/?blur=2",
    currency: "CNY",
    amount: 4.32,
  },
  {
    name: "Fairy penguin",
    imageUrl: "https://picsum.photos/200/300/?blur=2",
    currency: "IDR",
    amount: 6.07,
  },
  {
    name: "Black-throated cardinal",
    imageUrl: "https://picsum.photos/200/300/?blur=2",
    currency: "BRL",
    amount: 8.71,
  },
  {
    name: "Turaco, violet-crested",
    imageUrl: "https://picsum.photos/200/300/?blur=2",
    currency: "CNY",
    amount: 4.6,
  },
  {
    name: "Blackish oystercatcher",
    imageUrl: "https://picsum.photos/200/300/?blur=2",
    currency: "JPY",
    amount: 0.07,
  },
  {
    name: "Egyptian cobra",
    imageUrl: "https://picsum.photos/200/300/?blur=2",
    currency: "CNY",
    amount: 1.91,
  },
  {
    name: "White-browed owl",
    imageUrl: "https://picsum.photos/200/300/?blur=2",
    currency: "EUR",
    amount: 2.63,
  },
  {
    name: "Eagle owl (unidentified)",
    imageUrl: "https://picsum.photos/200/300/?blur=2",
    currency: "AFN",
    amount: 2.9,
  },
  {
    name: "Pine siskin",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 8.2,
  },
  {
    name: "Arctic lemming",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 4.1,
  },
  {
    name: "American bighorn sheep",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "EUR",
    amount: 3.26,
  },
  {
    name: "Crested porcupine",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "RUB",
    amount: 7.16,
  },
  {
    name: "Possum, golden brush-tailed",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "SYP",
    amount: 5.94,
  },
  {
    name: "Meerkat, red",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 0.2,
  },
  {
    name: "Rat, arboral spiny",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "COP",
    amount: 4.88,
  },
  {
    name: "Tenrec, tailless",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 2.35,
  },
  {
    name: "Pintail, white-cheeked",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "JPY",
    amount: 9.82,
  },
  {
    name: "European spoonbill",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 5.51,
  },
  {
    name: "Seal, harbor",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 2.46,
  },
  {
    name: "Cockatoo, sulfur-crested",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "USD",
    amount: 4.26,
  },
  {
    name: "Little blue penguin",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 7.96,
  },
  {
    name: "Capuchin, weeper",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "KRW",
    amount: 7.69,
  },
  {
    name: "Stork, white-necked",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "EUR",
    amount: 6.59,
  },
  {
    name: "Bee-eater, nubian",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "JPY",
    amount: 3.22,
  },
  {
    name: "Brush-tailed phascogale",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 6.85,
  },
  {
    name: "Gonolek, burchell's",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "KRW",
    amount: 3.52,
  },
  {
    name: "Snake, racer",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "THB",
    amount: 1.67,
  },
  {
    name: "Yellow-crowned night heron",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "NOK",
    amount: 8.17,
  },
  {
    name: "Tamandua, southern",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 6.29,
  },
  {
    name: "Southern elephant seal",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 4.74,
  },
  {
    name: "Common eland",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 2.52,
  },
  {
    name: "Sockeye salmon",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PLN",
    amount: 5.0,
  },
  {
    name: "African porcupine",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "RUB",
    amount: 6.15,
  },
  {
    name: "Black-crowned night heron",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 8.75,
  },
  {
    name: "Raccoon, common",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "RUB",
    amount: 2.87,
  },
  {
    name: "Wallaby, bennett's",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "AUD",
    amount: 7.69,
  },
  {
    name: "Lappet-faced vulture",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "MAD",
    amount: 0.34,
  },
  {
    name: "Blue catfish",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "SEK",
    amount: 2.5,
  },
  {
    name: "Cat, miner's",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 9.95,
  },
  {
    name: "European beaver",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 7.22,
  },
  {
    name: "Common pheasant",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "ARS",
    amount: 1.46,
  },
  {
    name: "Gelada baboon",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "RUB",
    amount: 9.7,
  },
  {
    name: "Stork, marabou",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 4.13,
  },
  {
    name: "Eastern diamondback rattlesnake",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 4.84,
  },
  {
    name: "Fox, arctic",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "AZN",
    amount: 7.16,
  },
  {
    name: "Polar bear",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "PGK",
    amount: 7.97,
  },
  {
    name: "Tenrec, tailless",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "RUB",
    amount: 0.34,
  },
  {
    name: "Snake, green vine",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "AZN",
    amount: 2.45,
  },
  {
    name: "Dove, laughing",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "AFN",
    amount: 1.48,
  },
  {
    name: "Denham's bustard",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "HNL",
    amount: 8.28,
  },
  {
    name: "Blackbuck",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 6.72,
  },
  {
    name: "Civet, common palm",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "PLN",
    amount: 8.29,
  },
  {
    name: "Jungle cat",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "BRL",
    amount: 1.04,
  },
  {
    name: "Tern, white-winged",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EUR",
    amount: 4.17,
  },
  {
    name: "Beaver, american",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "UAH",
    amount: 6.46,
  },
  {
    name: "Shrew, mandras tree",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EGP",
    amount: 9.34,
  },
  {
    name: "Shark, blue",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "BWP",
    amount: 1.95,
  },
  {
    name: "Eagle, white-bellied sea",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EUR",
    amount: 9.83,
  },
  {
    name: "White-winged dove",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 8.57,
  },
  {
    name: "Egret, cattle",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "RSD",
    amount: 6.41,
  },
  {
    name: "King vulture",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "UAH",
    amount: 3.71,
  },
  {
    name: "Lava gull",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EUR",
    amount: 8.58,
  },
  {
    name: "Eastern fox squirrel",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "AFN",
    amount: 1.15,
  },
  {
    name: "Dusky gull",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "SEK",
    amount: 5.0,
  },
  {
    name: "Cormorant, neotropic",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 8.85,
  },
  {
    name: "Quoll, spotted-tailed",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 0.63,
  },
  {
    name: "Owl, white-browed",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "BRL",
    amount: 7.5,
  },
  {
    name: "Mexican wolf",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "BRL",
    amount: 7.95,
  },
  {
    name: "Penguin, galapagos",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 9.88,
  },
  {
    name: "Madagascar hawk owl",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 0.39,
  },
  {
    name: "Western palm tanager (unidentified)",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 0.8,
  },
  {
    name: "Nuthatch, red-breasted",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 0.76,
  },
  {
    name: "Kangaroo, red",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "GHS",
    amount: 3.66,
  },
  {
    name: "Wolf, timber",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 8.17,
  },
  {
    name: "Cormorant, javanese",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "LYD",
    amount: 5.22,
  },
  {
    name: "Pie, rufous tree",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "PEN",
    amount: 0.15,
  },
  {
    name: "Squirrel, thirteen-lined",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 7.0,
  },
  {
    name: "Alligator, american",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "UAH",
    amount: 7.36,
  },
  {
    name: "Elegant crested tinamou",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "RUB",
    amount: 0.74,
  },
  {
    name: "Common wallaroo",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 4.69,
  },
  {
    name: "Arctic ground squirrel",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "USD",
    amount: 0.94,
  },
  {
    name: "Ox, musk",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "JPY",
    amount: 7.65,
  },
  {
    name: "Lemur, brown",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 9.91,
  },
  {
    name: "American alligator",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "JPY",
    amount: 2.82,
  },
  {
    name: "Rhinoceros, black",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "PHP",
    amount: 3.88,
  },
  {
    name: "Laughing kookaburra",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "SEK",
    amount: 1.41,
  },
  {
    name: "Eagle, bald",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "AZN",
    amount: 6.36,
  },
  {
    name: "Crane, brolga",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "KES",
    amount: 2.55,
  },
  {
    name: "White-throated toucan",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "NGN",
    amount: 1.36,
  },
  {
    name: "Nubian bee-eater",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "BRL",
    amount: 0.78,
  },
  {
    name: "Squirrel, grey-footed",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EUR",
    amount: 6.32,
  },
  {
    name: "Guanaco",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CZK",
    amount: 1.71,
  },
  {
    name: "Bird, pied butcher",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EUR",
    amount: 5.62,
  },
  {
    name: "Skunk, western spotted",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "RUB",
    amount: 5.9,
  },
  {
    name: "Goose, spur-winged",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "RUB",
    amount: 6.06,
  },
  {
    name: "Raccoon dog",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 7.78,
  },
  {
    name: "African porcupine",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 5.73,
  },
  {
    name: "White-necked stork",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "NGN",
    amount: 4.5,
  },
  {
    name: "Chameleon (unidentified)",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 9.65,
  },
  {
    name: "Dingo",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "PEN",
    amount: 3.4,
  },
  {
    name: "Sockeye salmon",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "UAH",
    amount: 0.93,
  },
  {
    name: "Dolphin, striped",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "BRL",
    amount: 2.59,
  },
  {
    name: "Corella, long-billed",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EUR",
    amount: 4.37,
  },
  {
    name: "Oryx, beisa",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "BRL",
    amount: 0.61,
  },
  {
    name: "Buffalo, american",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 8.15,
  },
  {
    name: "Two-toed sloth",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EUR",
    amount: 0.06,
  },
  {
    name: "Eurasian badger",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 6.8,
  },
  {
    name: "African skink",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 3.67,
  },
  {
    name: "Genet, common",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 3.57,
  },
  {
    name: "Spectacled caiman",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 0.09,
  },
  {
    name: "Pronghorn",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "KRW",
    amount: 4.0,
  },
  {
    name: "Snake, green vine",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "KZT",
    amount: 1.35,
  },
  {
    name: "Vulture, black",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EUR",
    amount: 7.21,
  },
  {
    name: "Indian jackal",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 3.56,
  },
  {
    name: "Lily trotter",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "USD",
    amount: 0.73,
  },
  {
    name: "Baboon, gelada",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EUR",
    amount: 3.95,
  },
  {
    name: "Galapagos mockingbird",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "JPY",
    amount: 9.71,
  },
  {
    name: "Eagle, white-bellied sea",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "UAH",
    amount: 8.55,
  },
  {
    name: "White-fronted capuchin",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 8.87,
  },
  {
    name: "Brown antechinus",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "BRL",
    amount: 2.2,
  },
  {
    name: "Asian water dragon",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IRR",
    amount: 3.14,
  },
  {
    name: "Common raccoon",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "IDR",
    amount: 4.76,
  },
  {
    name: "Blue fox",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "EUR",
    amount: 5.75,
  },
  {
    name: "Ground monitor (unidentified)",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CAD",
    amount: 1.55,
  },
  {
    name: "Lemming, collared",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 2.36,
  },
  {
    name: "Savanna baboon",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "RUB",
    amount: 8.19,
  },
  {
    name: "Mexican wolf",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "PHP",
    amount: 2.79,
  },
  {
    name: "Tammar wallaby",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "SEK",
    amount: 6.71,
  },
  {
    name: "Wallaroo, common",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "ZWL",
    amount: 7.85,
  },
  {
    name: "Glider, feathertail",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 1.67,
  },
  {
    name: "Monkey, rhesus",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "SEK",
    amount: 4.33,
  },
  {
    name: "Squirrel, thirteen-lined",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "VEF",
    amount: 9.88,
  },
  {
    name: "Heron, grey",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "ETB",
    amount: 5.58,
  },
  {
    name: "Long-necked turtle",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "BRL",
    amount: 9.56,
  },
  {
    name: "Field flicker",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "USD",
    amount: 7.4,
  },
  {
    name: "Short-nosed bandicoot",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "XAF",
    amount: 1.85,
  },
  {
    name: "Crane, wattled",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 2.43,
  },
  {
    name: "Pintail, bahama",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "UAH",
    amount: 3.32,
  },
  {
    name: "Baboon, chacma",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "UAH",
    amount: 10.0,
  },
  {
    name: "Snake, racer",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 4.97,
  },
  {
    name: "Jacana, african",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PEN",
    amount: 1.12,
  },
  {
    name: "Wattled crane",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "SDG",
    amount: 5.38,
  },
  {
    name: "Shrike, southern white-crowned",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "COP",
    amount: 7.78,
  },
  {
    name: "Gerenuk",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 4.41,
  },
  {
    name: "Harbor seal",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "UAH",
    amount: 7.39,
  },
  {
    name: "Wild water buffalo",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "LYD",
    amount: 2.67,
  },
  {
    name: "Stilt, black-winged",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "XOF",
    amount: 8.02,
  },
  {
    name: "Swan, trumpeter",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "RSD",
    amount: 4.19,
  },
  {
    name: "Springhare",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "THB",
    amount: 4.67,
  },
  {
    name: "Wallaby, agile",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "THB",
    amount: 1.07,
  },
  {
    name: "Red-billed tropic bird",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "AFN",
    amount: 9.63,
  },
  {
    name: "Boa, malagasy ground",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PHP",
    amount: 3.59,
  },
  {
    name: "Jackal, golden",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 7.14,
  },
  {
    name: "Trotter, lily",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 0.34,
  },
  {
    name: "Kangaroo, brush-tailed rat",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PHP",
    amount: 5.06,
  },
  {
    name: "Wolf spider",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "RUB",
    amount: 9.25,
  },
  {
    name: "White rhinoceros",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "EUR",
    amount: 8.75,
  },
  {
    name: "Stork, black-necked",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "RUB",
    amount: 4.71,
  },
  {
    name: "Roseat flamingo",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "BGN",
    amount: 8.13,
  },
  {
    name: "Crow, house",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "BRL",
    amount: 4.7,
  },
  {
    name: "Opossum, american virginia",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "EUR",
    amount: 2.23,
  },
  {
    name: "Eastern box turtle",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "USD",
    amount: 9.87,
  },
  {
    name: "Cape white-eye",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "USD",
    amount: 7.21,
  },
  {
    name: "Woylie",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PHP",
    amount: 3.33,
  },
  {
    name: "Magistrate black colobus",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "MWK",
    amount: 2.49,
  },
  {
    name: "Flamingo, greater",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "ZAR",
    amount: 3.85,
  },
  {
    name: "African buffalo",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "UAH",
    amount: 4.05,
  },
  {
    name: "Lizard, desert spiny",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 0.75,
  },
  {
    name: "Nelson ground squirrel",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 6.57,
  },
  {
    name: "Asian water buffalo",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "KHR",
    amount: 8.73,
  },
  {
    name: "European shelduck",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CZK",
    amount: 2.17,
  },
  {
    name: "Stanley bustard",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PHP",
    amount: 5.22,
  },
  {
    name: "Albatross, waved",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "EUR",
    amount: 8.33,
  },
  {
    name: "Richardson's ground squirrel",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "SEK",
    amount: 9.67,
  },
  {
    name: "Alligator, american",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "USD",
    amount: 3.82,
  },
  {
    name: "Fox, silver-backed",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 4.84,
  },
  {
    name: "Sun gazer",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 6.86,
  },
  {
    name: "Tortoise, asian foreset",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "ARS",
    amount: 7.1,
  },
  {
    name: "Ground monitor (unidentified)",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 2.08,
  },
  {
    name: "Grenadier, purple",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 3.46,
  },
  {
    name: "Roseate cockatoo",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "BRL",
    amount: 9.48,
  },
  {
    name: "Gecko, bent-toed",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PHP",
    amount: 4.15,
  },
  {
    name: "Boa, mexican",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "HRK",
    amount: 1.76,
  },
  {
    name: "Monitor, two-banded",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 8.16,
  },
  {
    name: "Snake, carpet",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PHP",
    amount: 6.23,
  },
  {
    name: "Wildebeest, blue",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "EUR",
    amount: 4.02,
  },
  {
    name: "Great white pelican",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PHP",
    amount: 0.18,
  },
  {
    name: "Loris, slender",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "THB",
    amount: 9.39,
  },
  {
    name: "Baboon, yellow",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "BRL",
    amount: 2.21,
  },
  {
    name: "Partridge, coqui",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "EUR",
    amount: 3.27,
  },
  {
    name: "Crab (unidentified)",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 2.65,
  },
  {
    name: "Giraffe",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "JPY",
    amount: 9.34,
  },
  {
    name: "Red-necked phalarope",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CAD",
    amount: 8.76,
  },
  {
    name: "Sarus crane",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 1.12,
  },
  {
    name: "Monkey, red howler",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "UAH",
    amount: 4.24,
  },
  {
    name: "Collared peccary",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "EUR",
    amount: 1.42,
  },
  {
    name: "Violet-crested turaco",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "JPY",
    amount: 8.98,
  },
  {
    name: "Cat, european wild",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "EUR",
    amount: 5.3,
  },
  {
    name: "Ring-tailed possum",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "RUB",
    amount: 5.03,
  },
  {
    name: "Impala",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "RWF",
    amount: 1.42,
  },
  {
    name: "White stork",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 7.92,
  },
  {
    name: "Southern hairy-nosed wombat",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CZK",
    amount: 7.48,
  },
  {
    name: "Fowl, helmeted guinea",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "BYR",
    amount: 4.29,
  },
  {
    name: "Southern tamandua",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 3.61,
  },
  {
    name: "Tern, arctic",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "ETB",
    amount: 9.21,
  },
  {
    name: "Ringtail",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "EGP",
    amount: 3.18,
  },
  {
    name: "Australian pelican",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PLN",
    amount: 7.27,
  },
  {
    name: "Tailless tenrec",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "SYP",
    amount: 4.94,
  },
  {
    name: "Harbor seal",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "JPY",
    amount: 2.79,
  },
  {
    name: "Baboon, olive",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PLN",
    amount: 7.44,
  },
  {
    name: "Red squirrel",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "BRL",
    amount: 7.4,
  },
  {
    name: "Possum, common brushtail",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 6.49,
  },
  {
    name: "Ferret, black-footed",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "THB",
    amount: 7.58,
  },
  {
    name: "Steenbok",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 6.47,
  },
  {
    name: "White-browed sparrow weaver",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 7.88,
  },
  {
    name: "Southern sea lion",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CZK",
    amount: 7.83,
  },
  {
    name: "Catfish, blue",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PLN",
    amount: 6.71,
  },
  {
    name: "Porcupine, crested",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 5.23,
  },
  {
    name: "Fox, blue",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "RUB",
    amount: 7.79,
  },
  {
    name: "Painted stork",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "THB",
    amount: 1.24,
  },
  {
    name: "Lechwe, kafue flats",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "NGN",
    amount: 2.67,
  },
  {
    name: "Lesser masked weaver",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "RSD",
    amount: 6.73,
  },
  {
    name: "Indian jackal",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "RUB",
    amount: 0.89,
  },
  {
    name: "Badger, honey",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 2.68,
  },
  {
    name: "Frilled lizard",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "GTQ",
    amount: 9.87,
  },
  {
    name: "Alpaca",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "RUB",
    amount: 2.06,
  },
  {
    name: "Red-billed buffalo weaver",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 9.09,
  },
  {
    name: "Swainson's francolin",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "ILS",
    amount: 1.43,
  },
  {
    name: "Brown hyena",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "TMT",
    amount: 6.17,
  },
  {
    name: "Gull, southern black-backed",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 8.82,
  },
  {
    name: "Heron, green-backed",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "EUR",
    amount: 1.79,
  },
  {
    name: "Sifaka, verreaux's",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "SEK",
    amount: 0.8,
  },
  {
    name: "Lion, southern sea",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "SEK",
    amount: 4.0,
  },
  {
    name: "Sportive lemur",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "BGN",
    amount: 8.7,
  },
  {
    name: "Dabchick",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 2.63,
  },
  {
    name: "Ring dove",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "BAM",
    amount: 2.08,
  },
  {
    name: "Vulture, white-headed",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "MUR",
    amount: 3.28,
  },
  {
    name: "Chacma baboon",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 9.92,
  },
  {
    name: "Spotted-tailed quoll",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 5.66,
  },
  {
    name: "Red howler monkey",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "EUR",
    amount: 8.63,
  },
  {
    name: "Smith's bush squirrel",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "USD",
    amount: 5.4,
  },
  {
    name: "Ring dove",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 0.52,
  },
  {
    name: "Spectacled caiman",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "BRL",
    amount: 2.09,
  },
  {
    name: "Gray heron",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 8.82,
  },
  {
    name: "Stanley crane",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "MYR",
    amount: 9.8,
  },
  {
    name: "Burmese brown mountain tortoise",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 6.69,
  },
  {
    name: "Turtle (unidentified)",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "GMD",
    amount: 9.06,
  },
  {
    name: "Hartebeest, red",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "SEK",
    amount: 1.49,
  },
  {
    name: "White-tailed deer",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "JPY",
    amount: 4.17,
  },
  {
    name: "Brindled gnu",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "USD",
    amount: 5.71,
  },
  {
    name: "Common long-nosed armadillo",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CZK",
    amount: 9.5,
  },
  {
    name: "Pine snake (unidentified)",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "HNL",
    amount: 5.11,
  },
  {
    name: "Red-knobbed coot",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PEN",
    amount: 8.04,
  },
  {
    name: "White-nosed coatimundi",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 8.93,
  },
  {
    name: "Falcon, prairie",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "SEK",
    amount: 7.35,
  },
  {
    name: "Butterfly, tropical buckeye",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "BRL",
    amount: 9.45,
  },
  {
    name: "White-necked stork",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PHP",
    amount: 4.54,
  },
  {
    name: "Snake, western patch-nosed",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PHP",
    amount: 7.46,
  },
  {
    name: "Wombat, common",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 1.68,
  },
  {
    name: "Wallaby, bennett's",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 7.7,
  },
  {
    name: "Indian tree pie",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CAD",
    amount: 3.49,
  },
  {
    name: "Red hartebeest",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "COP",
    amount: 7.14,
  },
  {
    name: "Wildebeest, blue",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PHP",
    amount: 4.41,
  },
  {
    name: "Cat, kaffir",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PHP",
    amount: 9.23,
  },
  {
    name: "Sidewinder",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 5.72,
  },
  {
    name: "Chameleon (unidentified)",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 2.43,
  },
  {
    name: "White-tailed jackrabbit",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 0.05,
  },
  {
    name: "Desert kangaroo rat",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "UAH",
    amount: 8.2,
  },
  {
    name: "Pocket gopher (unidentified)",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "RUB",
    amount: 7.47,
  },
  {
    name: "Russian dragonfly",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 1.57,
  },
  {
    name: "Hornbill, yellow-billed",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PHP",
    amount: 3.34,
  },
  {
    name: "Crab-eating fox",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 4.2,
  },
  {
    name: "Langur, gray",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "KZT",
    amount: 2.88,
  },
  {
    name: "European stork",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PEN",
    amount: 6.39,
  },
  {
    name: "Eastern grey kangaroo",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 5.9,
  },
  {
    name: "Cat, native",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "EUR",
    amount: 5.42,
  },
  {
    name: "Flightless cormorant",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 2.29,
  },
  {
    name: "Lemming, collared",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "RUB",
    amount: 0.61,
  },
  {
    name: "Land iguana",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "RUB",
    amount: 5.06,
  },
  {
    name: "White-winged dove",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "VND",
    amount: 2.52,
  },
  {
    name: "Monkey, rhesus",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "MYR",
    amount: 6.95,
  },
  {
    name: "Brown pelican",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 4.65,
  },
  {
    name: "Common grenadier",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 7.9,
  },
  {
    name: "Skunk, striped",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 5.73,
  },
  {
    name: "Pie, indian tree",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "BYR",
    amount: 9.3,
  },
  {
    name: "Whip-tailed wallaby",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PEN",
    amount: 3.83,
  },
  {
    name: "Rhea, gray",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CLP",
    amount: 5.22,
  },
  {
    name: "Little brown dove",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "KWD",
    amount: 9.26,
  },
  {
    name: "Great kiskadee",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "VEF",
    amount: 7.0,
  },
  {
    name: "Impala",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "MGA",
    amount: 3.38,
  },
  {
    name: "Gray heron",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 0.78,
  },
  {
    name: "Vulture, bengal",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "EGP",
    amount: 2.69,
  },
  {
    name: "Spectacled caiman",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 9.85,
  },
  {
    name: "Sockeye salmon",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 1.56,
  },
  {
    name: "Frilled lizard",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 1.05,
  },
  {
    name: "Bushpig",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "XOF",
    amount: 0.87,
  },
  {
    name: "Puma, south american",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PEN",
    amount: 1.19,
  },
  {
    name: "Currasow (unidentified)",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "JPY",
    amount: 7.9,
  },
  {
    name: "Bobcat",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "BRL",
    amount: 4.76,
  },
  {
    name: "Caribou",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PHP",
    amount: 5.14,
  },
  {
    name: "Lemur, grey mouse",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "BRL",
    amount: 4.68,
  },
  {
    name: "Egret, great",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "LYD",
    amount: 0.58,
  },
  {
    name: "Crab-eating fox",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "NGN",
    amount: 1.27,
  },
  {
    name: "Red phalarope",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "IRR",
    amount: 4.87,
  },
  {
    name: "Weaver, chestnut",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "CNY",
    amount: 0.44,
  },
  {
    name: "Camel, dromedary",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "EUR",
    amount: 4.63,
  },
  {
    name: "Long-crested hawk eagle",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "CNY",
    amount: 4.33,
  },
  {
    name: "Magpie, black-backed",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "JMD",
    amount: 6.66,
  },
  {
    name: "Barking gecko",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "CNY",
    amount: 7.5,
  },
  {
    name: "Wood pigeon",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "PEN",
    amount: 7.13,
  },
  {
    name: "Dama wallaby",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "UAH",
    amount: 7.83,
  },
  {
    name: "Common eland",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "RUB",
    amount: 0.82,
  },
  {
    name: "River wallaby",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "EUR",
    amount: 5.14,
  },
  {
    name: "Timber wolf",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "ALL",
    amount: 9.38,
  },
  {
    name: "White-faced whistling duck",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "IDR",
    amount: 3.09,
  },
  {
    name: "American alligator",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "BRL",
    amount: 1.6,
  },
  {
    name: "Heron, striated",
    imageUrl: "https://unsplash.com/photos/y83Je1OC6Wc",
    currency: "ETB",
    amount: 0.83,
  },
  {
    name: "Anteater, giant",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "HUF",
    amount: 3.64,
  },
  {
    name: "Wild turkey",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "RUB",
    amount: 7.63,
  },
  {
    name: "Scarlet macaw",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "TZS",
    amount: 9.09,
  },
  {
    name: "Jackal, indian",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "COP",
    amount: 2.13,
  },
  {
    name: "Burrowing owl",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "RUB",
    amount: 3.27,
  },
  {
    name: "Green heron",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "MKD",
    amount: 2.74,
  },
  {
    name: "Field flicker",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "NOK",
    amount: 4.56,
  },
  {
    name: "Cape fox",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "MYR",
    amount: 5.26,
  },
  {
    name: "Lava gull",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 6.71,
  },
  {
    name: "Warthog",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 7.13,
  },
  {
    name: "Blue-breasted cordon bleu",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "BRL",
    amount: 9.77,
  },
  {
    name: "Waterbuck, defassa",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PLN",
    amount: 8.35,
  },
  {
    name: "Adouri (unidentified)",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 6.69,
  },
  {
    name: "Netted rock dragon",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 4.33,
  },
  {
    name: "Savanna fox",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "EUR",
    amount: 3.92,
  },
  {
    name: "Goose, greylag",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "COP",
    amount: 5.08,
  },
  {
    name: "Hartebeest, coke's",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "MYR",
    amount: 6.67,
  },
  {
    name: "Snake, buttermilk",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 2.22,
  },
  {
    name: "Legaan, Monitor (unidentified)",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "COP",
    amount: 4.49,
  },
  {
    name: "Royal tern",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "PLN",
    amount: 5.59,
  },
  {
    name: "Glossy starling (unidentified)",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "HTG",
    amount: 7.94,
  },
  {
    name: "Dragon, komodo",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "RUB",
    amount: 7.12,
  },
  {
    name: "Paca",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 0.78,
  },
  {
    name: "Giant girdled lizard",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "HNL",
    amount: 0.67,
  },
  {
    name: "Southern black-backed gull",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 9.43,
  },
  {
    name: "Black-tailed prairie dog",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "IDR",
    amount: 3.78,
  },
  {
    name: "Helmeted guinea fowl",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "RUB",
    amount: 3.82,
  },
  {
    name: "Argalis",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "THB",
    amount: 7.36,
  },
  {
    name: "European wild cat",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "DOP",
    amount: 5.55,
  },
  {
    name: "White-rumped vulture",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "EUR",
    amount: 1.37,
  },
  {
    name: "Russian dragonfly",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "CLP",
    amount: 3.86,
  },
  {
    name: "Baleen whale",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "SEK",
    amount: 9.29,
  },
  {
    name: "Drongo, fork-tailed",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "IDR",
    amount: 5.24,
  },
  {
    name: "Cape clawless otter",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "CNY",
    amount: 3.29,
  },
  {
    name: "Yellow baboon",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "IDR",
    amount: 2.9,
  },
  {
    name: "Roe deer",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "PHP",
    amount: 1.28,
  },
  {
    name: "Eastern boa constrictor",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "PHP",
    amount: 1.67,
  },
  {
    name: "Raven, white-necked",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "CNY",
    amount: 6.5,
  },
  {
    name: "Dove, ring",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "MGA",
    amount: 5.46,
  },
  {
    name: "Sloth bear",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "IDR",
    amount: 5.42,
  },
  {
    name: "Emu",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "EUR",
    amount: 5.15,
  },
  {
    name: "White-faced whistling duck",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "TZS",
    amount: 9.9,
  },
  {
    name: "Great white pelican",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "UAH",
    amount: 3.74,
  },
  {
    name: "Squirrel, grey-footed",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "IDR",
    amount: 4.01,
  },
  {
    name: "Alligator, mississippi",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "ILS",
    amount: 1.45,
  },
  {
    name: "Sparrow, house",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "IDR",
    amount: 5.52,
  },
  {
    name: "Scarlet macaw",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "PEN",
    amount: 7.25,
  },
  {
    name: "Vine snake (unidentified)",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "XCD",
    amount: 7.35,
  },
  {
    name: "Monitor, white-throated",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "EUR",
    amount: 9.1,
  },
  {
    name: "Magpie, black-backed",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "XAF",
    amount: 7.55,
  },
  {
    name: "Grey fox",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "USD",
    amount: 6.14,
  },
  {
    name: "Armadillo, giant",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "IDR",
    amount: 1.69,
  },
  {
    name: "European red squirrel",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "CNY",
    amount: 7.41,
  },
  {
    name: "Javanese cormorant",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "CLP",
    amount: 4.5,
  },
  {
    name: "Common palm civet",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "THB",
    amount: 5.16,
  },
  {
    name: "Spoonbill, european",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "PHP",
    amount: 6.15,
  },
  {
    name: "Malleefowl",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "EUR",
    amount: 6.44,
  },
  {
    name: "Water moccasin",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "RUB",
    amount: 8.5,
  },
  {
    name: "Trumpeter swan",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "EUR",
    amount: 5.77,
  },
  {
    name: "Shelduck, common",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "UAH",
    amount: 6.14,
  },
  {
    name: "Pigeon, feral rock",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "IDR",
    amount: 8.79,
  },
  {
    name: "Porcupine, african",
    imageUrl: "https://picsum.photos/200/300/?blur",
    currency: "EUR",
    amount: 7.33,
  },
  {
    name: "Paca",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "PEN",
    amount: 5.64,
  },
  {
    name: "Common wallaroo",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "PKR",
    amount: 4.98,
  },
  {
    name: "Shelduck, european",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "CNY",
    amount: 3.2,
  },
  {
    name: "Emerald-spotted wood dove",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "EUR",
    amount: 8.58,
  },
  {
    name: "Cat, ringtail",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "CNY",
    amount: 0.5,
  },
  {
    name: "Grison",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "JPY",
    amount: 2.01,
  },
  {
    name: "Cliffchat, mocking",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "IDR",
    amount: 5.36,
  },
  {
    name: "White spoonbill",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "EUR",
    amount: 6.31,
  },
  {
    name: "Gecko, bent-toed",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "CNY",
    amount: 2.19,
  },
  {
    name: "Long-tailed jaeger",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "USD",
    amount: 8.45,
  },
  {
    name: "White-bellied sea eagle",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "PHP",
    amount: 6.25,
  },
  {
    name: "Shrike, crimson-breasted",
    imageUrl: "https://unsplash.com/photos/tCICLJ5ktBE",
    currency: "CUP",
    amount: 5.96,
  },
  {
    name: "Great egret",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "BYR",
    amount: 4.44,
  },
  {
    name: "Bottle-nose dolphin",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "CAD",
    amount: 1.51,
  },
  {
    name: "Gray langur",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "EUR",
    amount: 2.08,
  },
  {
    name: "Cat, tiger",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    amount: 3.57,
  },
  {
    name: "Barrows goldeneye",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "CNY",
    amount: 1.27,
  },
  {
    name: "Goose, knob-nosed",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "JOD",
    amount: 0.87,
  },
  {
    name: "Red-capped cardinal",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "IDR",
    amount: 5.24,
  },
  {
    name: "Squirrel, nelson ground",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "HNL",
    amount: 0.15,
  },
  {
    name: "American Virginia opossum",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "XOF",
    amount: 5.27,
  },
  {
    name: "Dunnart, fat-tailed",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "EUR",
    amount: 2.21,
  },
  {
    name: "Southern right whale",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "CNY",
    amount: 6.3,
  },
  {
    name: "Crested screamer",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "CNY",
    amount: 6.05,
  },
  {
    name: "Francolin, coqui",
    imageUrl: "https://unsplash.com/photos/iJnZwLBOB1I",
    currency: "JPY",
    amount: 5.19,
  },
  {
    name: "Pacific gull",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "VND",
    amount: 4.28,
  },
  {
    name: "Sally lightfoot crab",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "BAM",
    amount: 5.29,
  },
  {
    name: "Yellow-bellied marmot",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "XOF",
    amount: 1.2,
  },
  {
    name: "Savannah deer",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "MNT",
    amount: 8.04,
  },
  {
    name: "Skink, blue-tongued",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "BGN",
    amount: 3.58,
  },
  {
    name: "Ringtail cat",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "PLN",
    amount: 1.58,
  },
  {
    name: "Blue peacock",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "ALL",
    amount: 4.71,
  },
  {
    name: "Crane, sandhill",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "KRW",
    amount: 6.52,
  },
  {
    name: "Salmon, sockeye",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 0.2,
  },
  {
    name: "Wolf, mexican",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "BRL",
    amount: 3.8,
  },
  {
    name: "Lynx, african",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "RUB",
    amount: 7.24,
  },
  {
    name: "Elk, Wapiti",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "XOF",
    amount: 4.78,
  },
  {
    name: "Weaver, sociable",
    imageUrl: "https://picsum.photos/200/300.jpg",
    currency: "CNY",
    amount: 4.54,
  },
  {
    name: "Openbill stork",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "EUR",
    amount: 2.94,
  },
  {
    name: "Greater flamingo",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "EUR",
    amount: 2.38,
  },
  {
    name: "Blue wildebeest",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "PHP",
    amount: 8.41,
  },
  {
    name: "Eagle, pallas's fish",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "PLN",
    amount: 2.6,
  },
  {
    name: "Beaver, north american",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "CNY",
    amount: 7.86,
  },
  {
    name: "European beaver",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "CNY",
    amount: 2.25,
  },
  {
    name: "Hanuman langur",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "PLN",
    amount: 9.75,
  },
  {
    name: "Mockingbird, galapagos",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "EUR",
    amount: 6.11,
  },
  {
    name: "Waved albatross",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "EUR",
    amount: 7.02,
  },
  {
    name: "Cheetah",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "BRL",
    amount: 8.33,
  },
  {
    name: "Meerkat",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "RUB",
    amount: 5.44,
  },
  {
    name: "Flicker, campo",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "PKR",
    amount: 8.03,
  },
  {
    name: "Woodpecker, downy",
    imageUrl: "https://unsplash.com/photos/Dl6jeyfihLk",
    currency: "EUR",
    amount: 6.68,
  },
  {
    name: "Flamingo, roseat",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "CDF",
    amount: 1.4,
  },
  {
    name: "Praying mantis (unidentified)",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "EUR",
    amount: 5.36,
  },
  {
    name: "Crane, stanley",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "CNY",
    amount: 9.62,
  },
  {
    name: "King cormorant",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "SEK",
    amount: 7.48,
  },
  {
    name: "Suricate",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "CNY",
    amount: 7.81,
  },
  {
    name: "Verreaux's sifaka",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "IDR",
    amount: 4.45,
  },
  {
    name: "Defassa waterbuck",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "CNY",
    amount: 3.91,
  },
  {
    name: "Stilt, black-winged",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "CNY",
    amount: 7.02,
  },
  {
    name: "Pheasant, ring-necked",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "PEN",
    amount: 4.27,
  },
  {
    name: "Chuckwalla",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "CNY",
    amount: 1.43,
  },
  {
    name: "Gazer, sun",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "CNY",
    amount: 6.4,
  },
  {
    name: "Common wombat",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "XAF",
    amount: 0.09,
  },
  {
    name: "Jackrabbit, white-tailed",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "RUB",
    amount: 5.02,
  },
  {
    name: "Puffin, horned",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "IDR",
    amount: 5.8,
  },
  {
    name: "Red lava crab",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "CLP",
    amount: 4.75,
  },
  {
    name: "Mongoose, small indian",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "CNY",
    amount: 9.88,
  },
  {
    name: "Goose, snow",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "PHP",
    amount: 4.91,
  },
  {
    name: "Ostrich",
    imageUrl: "https://unsplash.com/photos/LF8gK8-HGSg",
    currency: "UAH",
    amount: 1.61,
  },
  {
    name: "Fringe-eared oryx",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "HNL",
    amount: 3.86,
  },
  {
    name: "Otter, north american river",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 7.86,
  },
  {
    name: "Hyena, brown",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 6.48,
  },
  {
    name: "Horned puffin",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "MZN",
    amount: 8.93,
  },
  {
    name: "White-browed owl",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "RUB",
    amount: 9.91,
  },
  {
    name: "Jackrabbit, white-tailed",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 2.21,
  },
  {
    name: "White-faced tree rat",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "XOF",
    amount: 4.76,
  },
  {
    name: "Trumpeter, green-winged",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 2.48,
  },
  {
    name: "Rat, arboral spiny",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 9.8,
  },
  {
    name: "Ring dove",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "SEK",
    amount: 6.77,
  },
  {
    name: "Sandgrouse, yellow-throated",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PHP",
    amount: 2.94,
  },
  {
    name: "Grebe, little",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PEN",
    amount: 7.49,
  },
  {
    name: "Tern, white-winged",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CZK",
    amount: 8.27,
  },
  {
    name: "Peacock, blue",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "SEK",
    amount: 2.16,
  },
  {
    name: "White-winged dove",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 8.55,
  },
  {
    name: "Bald eagle",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "PHP",
    amount: 0.06,
  },
  {
    name: "Mockingbird, galapagos",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "EUR",
    amount: 8.77,
  },
  {
    name: "Burrowing owl",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "CNY",
    amount: 5.03,
  },
  {
    name: "African snake (unidentified)",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 2.25,
  },
  {
    name: "Little cormorant",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 7.34,
  },
  {
    name: "Heron, giant",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "MAD",
    amount: 1.75,
  },
  {
    name: "Hare, arctic",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "ILS",
    amount: 4.72,
  },
  {
    name: "Chacma baboon",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "IDR",
    amount: 1.31,
  },
  {
    name: "Blackbuck",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "JPY",
    amount: 7.54,
  },
  {
    name: "White-faced tree rat",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "MYR",
    amount: 8.27,
  },
  {
    name: "Asiatic jackal",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "USD",
    amount: 1.04,
  },
  {
    name: "Superb starling",
    imageUrl: "https://picsum.photos/200/300?grayscale",
    currency: "SYP",
    amount: 6.55,
  },
  {
    name: "Timber wolf",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "KES",
    amount: 9.03,
  },
  {
    name: "Western grey kangaroo",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "CNY",
    amount: 2.78,
  },
  {
    name: "Painted stork",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    currency: "USD",
    amount: 9.75,
  },
];

const productsWithCurrency = products.filter((product) => product.currency);

async function insertProducts() {
  try {
    await Product.insertMany(productsWithCurrency);
    console.log("Products inserted successfully");
  } catch (error) {
    console.error("Error inserting products:", error);
  } finally {
    mongoose.disconnect();
  }
}

insertProducts();
